cargo-featuresm = ["edition2024"]

[package]
name = "rust_inference"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
tch = "0.20.0"
tokio = "1.46.1"

[dependencies.uuid]
version = "1.17.0"
features = ["v4"]
